### ISSUE TITLE
unable to use trivy with intelliJ

### ISSUE THREAD

**Issue by prakashs-vibrent** [aquasecurity/intellij-trivy#18]
Please find below error i get when i run trivy plugin in intellij running on the windows 11 system.
Cannot run program "trivy": CreateProcess error=2, The system cannot find the file specified

additional error details : 
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.aquasecurity.plugins.trivy.actions.ClearResultsAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.aquasecurity.plugins.intellij-Trivy]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by prakashs-vibrent** [comment]
installing trivy on the local system and adding the installed path in IntelliJ resolved the issue
